# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    paths-ignore: 
      - 'docs/**'
      - 'reports/**'
      - '*.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore: 
      - 'docs/**'
      - 'reports/**'
      - '*.md'

jobs:

  build:
    environment: dev
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      working-directory: backend
      run: go build -v ./...

    - name: Test
      working-directory: backend
      run: go test -v ./...
